[package]
name = "conv"
version = "0.2.0"
authors = ["negamartin"]
edition = "2018"

[dependencies]
osu-db = { path = "..", features = ["ser-de"] }

anyhow = "1"
serde = "1"
ron = "0.6"
serde_json = "1"
fxhash = "0.2"
chrono = "0.4"
